os:
  - linux
dist: trusty
services:
  - docker
language: node_js
node_js:
  - "6.11.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=6.11.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - chmod +x gradlew
  - jdk_switcher use oraclejdk8
  - java -version
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - ./gradlew clean test sonarqube --stacktrace --info
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bootWar publish -Pprod -Pgraphite -Pprometheus -x test
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ./gradlew bootWar publish -Pprod -Pgraphite -Pprometheus -x test
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^release.*$"
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     #
