server:
    port: 8080
    servlet:
        session:
            cookie:
                http-only: true
eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: jobroom
        instanceId: jobroom:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
ribbon:
    eureka:
        enabled: true
    restclient:
        # must be set to false since otherwise the RibbonClientHttpRequestFactory is used which doesn't support 'PATCH'
        enabled: false

# See https://cloud.spring.io/spring-cloud-netflix/single/spring-cloud-netflix.html#_router_and_filter_zuul
zuul:
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500
    ignoreSecurityHeaders: false
    sensitiveHeaders:
        - Set-Cookie
        - Authorization
    ignoredServices:
        - alv-portal-webapp
    ignoredPatterns:
        # spring security saml
        - /saml/**
        # authentication redirection endpoints
        - /authentication/**
        - /login
        - /samllogin
        # jr2-ui
        - /jr2/**
        # gateway endpoints
        - /api/**
        # actuator endpoints
        - /management/**
        # swagger
        - /webjars/**
        - /swagger-ui.html
        - /swagger-resources
        - /swagger-resources/**
        - /v2/api-docs
    routes:
        jobdesk:
            path: /jobdesk/**
            serviceId: jobdesk-service
            strip-prefix: false
        portal-ui:
            path: /**
            serviceId: alv-portal-webapp

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    shareSecurityContext: true
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: when_authorized
            cache:
                time-to-live: 30s
    info:
        git:
            mode: simple

spring:
    application:
        name: jobroom
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.jdbc.lob.non_contextual_creation: true
            hibernate.id.new_generator_mappings: true
            hibernate.generate_statistics: true
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        cache: true
        mode: HTML
    liquibase:
        change-log: classpath:/config/liquibase/master.xml
    task:
        execution:
            thread-name-prefix: jr2-async
            pool:
                core-size: 2
                max-size: 50
                queue-capacity: 10000
        scheduling:
            thread-name-prefix: jr2-scheduler
            pool:
                size: 1
    cloud:
        stream:
            bindings:
                input:
                    group: jobroom
                    destination: candidate.event
            kafka:
                binder:
                    auto-add-partitions: true
                    auto-create-topics: true
                bindings:
                    input:
                        consumer:
                            enableDlq: true
                            dlq-name: candidate.event.dlq
    main:
        allow-bean-definition-overriding: true

info:
    project:
        version: #project.version#

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: http://www.jhipster.tech/common-application-properties/
# ===================================================================
jhipster:
    mail:
        from: jobroom@localhost
    gateway:
        authorized-microservices-endpoints:
            jobservice: /api,/v2/api-docs,/swagger-resources,/management
            referenceservice: /api,/v2/api-docs,/swagger-resources,/management
            candidateservice: /api,/v2/api-docs,/swagger-resources,/management
            jobadservice: /api,/v2/api-docs,/swagger-resources,/management

# ===================================================================
# Application specific properties
#
# ===================================================================
gateway:
    rate-limiting:
        enabled: true
        rate-filter-options:
            # Avoid fetching mass-fetching of sensitive candidate information
            - bucket-prefix: 'candidate-details'
              method: 'GET'
              url: '/candidateservice/api/candidates/*'
              limit: 5
              duration: 10s

            # apply rate-limiting filter to any request
            - bucket-prefix: 'all'
              url: '/**'
              limit: 100
              duration: 10s

security:
    eiam:
        rolemapping:
            ROLE_ALLOW: ALV-jobroom.ALLOW
            ROLE_REGISTRATION: ALV-jobroom.ROLE_REGISTRATION
            ROLE_USER: ALV-jobroom.ROLE_USER
            ROLE_JOBSEEKER_CLIENT: ALV-jobroom.ROLE_JOBSEEKER
            ROLE_PRIVATE_EMPLOYMENT_AGENT: ALV-jobroom.ROLE_PRIVATE_EMPLOYMENT_AGENT
            ROLE_COMPANY: ALV-jobroom.ROLE_COMPANY
            ROLE_PUBLIC_EMPLOYMENT_SERVICE: ALV-jobroom.ROLE_PUBLIC_EMPLOYMENT_SERVICE
            ROLE_ADMIN: ALV-jobroom.ROLE_ADMIN
            ROLE_SYSADMIN: ALV-jobroom.ROLE_SYSADMIN
        enable-redirect-on-cancellation: true
    user:
        logout_url: '/saml/logout'
        redirect-base-url:  ${jhipster.mail.base-url}
