-- The script adds three main roles and the respective users: stes (jobseeker), pav (hiring agent from the company) and the company account
-- jhipster users data
INSERT INTO jhi_user (id,
                      login,
                      password_hash,
                      first_name,
                      last_name,
                      gender,
                      email,
                      phone,
                      image_url,
                      activated,
                      lang_key,
                      activation_key,
                      reset_key,
                      organization_id,
                      created_by,
                      created_date,
                      reset_date,
                      last_modified_by,
                      last_modified_date)
VALUES ('00f9722b-7056-45b7-b10f-30db8a60afc5',
        'pav',
        '21232f297a57a5a743894a0e4a801fc3',
        'Eli',
        'Headhunter',
        null,
        'pav@localhost',
        null,
        null,
        true,
        'de',
        null,
        null,
        null,
        'system',
        '2018-09-28 14:49:54.544000',
        null,
        'system',
        null);

INSERT INTO jhi_user (id,
                      login,
                      password_hash,
                      first_name,
                      last_name,
                      gender,
                      email,
                      phone,
                      image_url,
                      activated,
                      lang_key,
                      activation_key,
                      reset_key,
                      organization_id,
                      created_by,
                      created_date,
                      reset_date,
                      last_modified_by,
                      last_modified_date)
VALUES ('00f9722b-7056-45b7-b10f-30db8a60afc1',
        'stes',
        '21232f297a57a5a743894a0e4a801fc3',
        'Jimmy',
        'Jobseeker',
        null,
        'stes@localhost',
        null,
        null,
        true,
        'en',
        null,
        null,
        null,
        'system',
        '2018-09-28 15:04:46.895000',
        null,
        'system',
        null);

INSERT INTO jhi_user (id,
                      login,
                      password_hash,
                      first_name,
                      last_name,
                      gender,
                      email,
                      phone,
                      image_url,
                      activated,
                      lang_key,
                      activation_key,
                      reset_key,
                      organization_id,
                      created_by,
                      created_date,
                      reset_date,
                      last_modified_by,
                      last_modified_date)
VALUES ('00f97223-7056-45b7-b10f-30db8a60afc2',
        'company',
        '21232f297a57a5a743894a0e4a801fc3',
        'Eli',
        'Company',
        null,
        'company@localhost',
        null,
        null,
        true,
        'fr',
        null,
        null,
        null,
        'system',
        '2018-09-28 15:12:14.414000',
        null,
        'system',
        null);

-- assigning the roles to our users
INSERT INTO jhi_user_authority (user_id, authority_name)
VALUES ('00f9722b-7056-45b7-b10f-30db8a60afc5', 'ROLE_PRIVATE_EMPLOYMENT_AGENT');

INSERT INTO jhi_user_authority (user_id, authority_name)
VALUES ('00f9722b-7056-45b7-b10f-30db8a60afc1', 'ROLE_JOBSEEKER_CLIENT');

INSERT INTO jhi_user_authority (user_id, authority_name)
VALUES ('00f97223-7056-45b7-b10f-30db8a60afc2', 'ROLE_COMPANY');

-- creating companies for company user and pav user
INSERT INTO company (id, external_id, name, street, zip_code, city, email, phone, source)
VALUES ('1234',
        'abcd',
        'mimacom headhunter',
        'Pav Street',
        '8000',
        'bern',
        '',
        null,
        'AVG');

INSERT INTO company (id, external_id, name, street, zip_code, city, email, phone, source)
VALUES ('5678',
        'comp1',
        'mimacom bern',
        'Company Steet',
        '3000',
        'bern',
        null,
        null,
        'UID');

-- system users data
INSERT INTO user_info (id,
                       external_id,
                       first_name,
                       last_name,
                       email,
                       phone,
                       lang_key,
                       access_code,
                       registration_status,
                       created_at,
                       modified_at,
                       last_login_at,
                       stes_person_number,
                       stes_verification_type,
                       stes_verified_at)
VALUES ('567462d5-c32e-11e8-bb4b-0242ac120002',
        'pav',
        'Eli',
        'Headhunter',
        'pav@localhost',
        null,
        'de',
        null,
        'REGISTERED',
        '2018-09-28 14:54:02.118000',
        '2018-09-28 14:58:58.036000',
        '2018-09-28 14:58:58.036000',
        null,
        null,
        null);

INSERT INTO user_info (id,
                       external_id,
                       first_name,
                       last_name,
                       email,
                       phone,
                       lang_key,
                       access_code,
                       registration_status,
                       created_at,
                       modified_at,
                       last_login_at,
                       stes_person_number,
                       stes_verification_type,
                       stes_verified_at)
VALUES ('f8e4714d-c32f-11e8-bb4b-0242ac120002',
        'stes',
        'Jimmy',
        'Jobseeker',
        'stes@localhost',
        null,
        'en',
        null,
        'REGISTERED',
        '2018-09-28 15:05:44.140000',
        '2018-09-28 15:09:27.265000',
        '2018-09-28 15:09:27.265000',
        999,
        'SIMPLE',
        '2018-09-28 15:07:54.625000');

INSERT INTO user_info (id,
                       external_id,
                       first_name,
                       last_name,
                       email,
                       phone,
                       lang_key,
                       access_code,
                       registration_status,
                       created_at,
                       modified_at,
                       last_login_at,
                       stes_person_number,
                       stes_verification_type,
                       stes_verified_at)
VALUES ('4bce11e6-c331-11e8-bb4b-0242ac120002',
        'company',
        'Eli',
        'Company',
        'company@localhost',
        null,
        'fr',
        null,
        'UNREGISTERED',
        '2018-09-28 15:15:12.741000',
        '2018-09-28 15:15:12.741000',
        '2018-09-28 15:15:12.741000',
        null,
        null,
        null);

-- assigning the pav and the company users to their respective companies
INSERT INTO accountability (user_id, accountability_type, company_id)
VALUES ('567462d5-c32e-11e8-bb4b-0242ac120002', 'USER', '1234');

INSERT INTO accountability (user_id, accountability_type, company_id)
VALUES ('4bce11e6-c331-11e8-bb4b-0242ac120002', 'USER', '5678');
