version: '3.3'
services:
    jobroom-app:
        build: dockerfiles/jobroom
        image: localhost:5000/jr2_jobroom-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8080
        ports:
            - 8080:8080
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    jobroom-app-eiam:
        build: dockerfiles/jobroom-eiam
        image: localhost:5000/jr2_jobroom-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8444
        ports:
            - 8444:8444
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    jobservice-app:
        build: dockerfiles/jobservice
        image: localhost:5000/jr2_jobservice-app
        env_file: apps-env.properties
        environment:
            LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8081
#        ports:
#            - 8081:8081
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    referenceservice-app:
        build: dockerfiles/referenceservice
        image: localhost:5000/jr2_referenceservice-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8082
#        ports:
#            - 8082:8082
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    candidateservice-app:
        build: dockerfiles/candidateservice
        image: localhost:5000/jr2_candidateservice-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8083
#        ports:
#            - 8083:8083
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == infr]

    jobroom-batch:
        build: dockerfiles/jobroom_batch
        image: localhost:5000/jr2_jobroom-batch
        env_file: apps-env.properties
        environment:
            SPRING_PROFILES_ACTIVE: development
            SPRING_APPLICATION_NAME: jobroom_batch
            SERVER_PORT: 9000
 #       ports:
 #           - 9000:9000
        volumes:
            - batch-tmp-data:/tmp/batch/
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

#    jobpublicationservice-app:
#        build: dockerfiles/jobpublicationservice
#        image: localhost:5000/jr2_jobpublicationservice-app
#        env_file: apps-env.properties
#        environment:
#            LIQUIBASE_ENABLED: false
#            SERVER_PORT: 8084
##        ports:
##            - 8084:8084
#        networks:
#            - jobroom_data2
#        secrets:
#            - source: bootstrap.yml-1
#              target: bootstrap.yml
#        deploy:
#            placement:
#                constraints: [node.labels.type == infr]

    trackingservice-app:
        build: dockerfiles/trackingservice
        image: localhost:5000/jr2_trackingservice-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_ENABLED: 'false'
            SERVER_PORT: 8085
#        ports:
#            - 8085:8085
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == infr]

    jobadservice-app:
        build: dockerfiles/jobadservice
        image: localhost:5000/jr2_jobadservice-app
        env_file: apps-env.properties
        environment:
            SPRING_LIQUIBASE_DROPFIRST: 'false'
            SERVER_PORT: 8086
        ports:
            - 8086:8086
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    checkuptool-app:
        build: dockerfiles/checkuptool
        image: localhost:5000/jr2_checkuptool-app
        env_file: apps-env.properties
        environment:
            SERVER_PORT: 8087
        ports:
            - 8087:8087
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]


volumes:
    batch-tmp-data:
        driver: local

networks:
    jobroom_data2:
        external: true

secrets:
    bootstrap.yml-1:
        external: true
