version: '3.4'
services:
    jobroom-batch-oracle:
        image: container-registry.oracle.com/database/enterprise:12.2.0.1
        environment:
            - DB_SID=orcl
        ports:
           - 1521:1521
           - 5500:5500
        volumes:
           - jobroom-batch-data:/ORCL
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.type == data]

volumes:
    jobroom-batch-data:
        driver: local

networks:
    jobroom_data2:
        external: true

