version: '3.4'
services:
    jobroom-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=jobroom
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5434:5432
        volumes:
            - jobroom-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=jobservice
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5435:5432
        volumes:
            - jobservice-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    candidateservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=candidateservice
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5436:5432
        volumes:
            - candidateservice-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    referenceservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=referenceservice
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5437:5432
        volumes:
            - referenceservice-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    trackingservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=trackingservice
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5438:5432
        volumes:
            - trackingservice-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobadservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=jobadservice
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        ports:
            - 5439:5432
        volumes:
            - jobadservice-data:/var/lib/postgresql/data
        networks:
            - jobroom_data2
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobroom-kibana:
        image: kibana:5
        env_file: env.properties
        ports:
            - 5601:5601
        environment:
            - xpack.security.enabled=false
            - ELASTICSEARCH_URL=http://jobroom-elasticsearch:9200
        links:
            - jobroom-elasticsearch:elasticsearch
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobroom-elasticsearch:
        image: elasticsearch:5
        env_file: env.properties
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
        command: -Ecluster.name=jobroom-cluster -Enetwork.host=0.0.0.0
        environment:
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m -Duser.timezone=Europe/Zurich
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.type == data]
            resources:
                limits:
                    memory: 2G

volumes:
    jobroom-data:
        driver: local
    jobservice-data:
        driver: local
    candidateservice-data:
        driver: local
    referenceservice-data:
        driver: local
    trackingservice-data:
        driver: local
    jobadservice-data:
        driver: local
    elasticsearch-data:
        driver: local
    jobroom-batch-data:
        driver: local
    spring-cloud-dataflow-data:
        driver: local

networks:
    jobroom_data2:
        external: true

secrets:
    postgres-passwd:
        external: true

