version: '3.4'
services:
    jobroom-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=jobroom
            - POSTGRES_PASSWORD=s3cr3t
        ports:
            - 5434:5432
        volumes:
            - jobroom_data:/var/lib/postgresql/data
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=jobservice
            - POSTGRES_PASSWORD=s3cr3t
        ports:
            - 5435:5432
        volumes:
            - jobservice_data:/var/lib/postgresql/data
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]

    candidateservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=candidateservice
            - POSTGRES_PASSWORD=s3cr3t
        ports:
            - 5436:5432
        volumes:
            - candidateservice_data:/var/lib/postgresql/data
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]

    referenceservice-postgres:
        image: postgres:latest
        environment:
            - TZ=Europe/Zurich
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=referenceservice
            - POSTGRES_PASSWORD=s3cr3t
        ports:
            - 5437:5432
        volumes:
            - referenceservice_data:/var/lib/postgresql/data
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobroom-kibana:
        image: kibana:5
        env_file: env.properties
        ports:
            - 5601:5601
        environment:
            - xpack.security.enabled=false
            - ELASTICSEARCH_URL=http://jobroom-elasticsearch:9200
        links:
            - jobroom-elasticsearch:elasticsearch
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]

    jobroom-elasticsearch:
        image: elasticsearch:5
        env_file: env.properties
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
        command: -Ecluster.name=jobroom-cluster -Enetwork.host=0.0.0.0
        environment:
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m -Duser.timezone=Europe/Zurich
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - jobroom
        deploy:
            placement:
                constraints: [node.labels.type == data]
            resources:
                limits:
                    memory: 2G

volumes:
    jobroom-data:
        driver: local
    jobservice-data:
        driver: local
    candidateservice-data:
        driver: local
    referenceservice-data:
        driver: local
    elasticsearch-data:
        driver: local

networks:
    jobroom:
        driver: overlay

