version: '3.4'
services:
    jobroom-app:
        build: dockerfiles/jobroom
        image: localhost:5000/docker_jobroom-app
        env_file: env.properties
        environment:
            - SLEEP=0
        ports:
            - 8443:8443
        volumes:
            - ./config:/config
        networks:
            - jobroom
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]
    jobservice-app:
        build: dockerfiles/jobservice
        image: localhost:5000/docker_jobservice-app
        env_file: env.properties
        environment:
            - SLEEP=0
            - LIQUIBASE_DROPFIRST=false
        ports:
            - 8444:8444
        volumes:
            - ./config:/config
        networks:
            - jobroom
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]
    referenceservice-app:
        build: dockerfiles/referenceservice
        image: localhost:5000/docker_referenceservice-app
        env_file: env.properties
        environment:
            - SLEEP=0
            - LIQUIBASE_DROPFIRST=false
        ports:
            - 8445:8445
        volumes:
            - ./config:/config
        networks:
            - jobroom
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]
    candidateservice-app:
        build: dockerfiles/candidateservice
        image: localhost:5000/docker_candidateservice-app
        env_file: env.properties
        environment:
            - SLEEP=0
            - LIQUIBASE_DROPFIRST=false
        ports:
            - 8446:8446
        volumes:
            - ./config:/config
        networks:
            - jobroom
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]
    jobroom-batch:
        build: dockerfiles/jobroom_batch
        image: localhost:5000/docker_jobroom-batch
        env_file: env.properties
        environment:
            - SPRING_PROFILES_ACTIVE=development
            - SLEEP=0
        ports:
            - 9000:9000
        volumes:
            - ./config:/config
            - batch-data:/build
            - /tmp/sftp-inbound:/tmp/sftp-inbound
        networks:
            - jobroom
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

volumes:
    batch-data:
        driver: local

networks:
    jobroom:
        driver: overlay
    jobroom_data2:
        external: true

secrets:
    bootstrap.yml-1:
        external: true

