version: '2'
services:
    jobroom-app:
        build: dockerfiles/jobroom
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit 
            - SPRING_PROFILES_ACTIVE=development,swagger
            - SPRING_CLOUD_CONFIG_URI=https://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_CLOUD_CONFIG_LABEL=master
            - SLEEP=40
        ports:
            - 8443:8443
        volumes:
            - ./config:/config
    jobservice-app:
        build: dockerfiles/jobservice
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
            - SPRING_PROFILES_ACTIVE=development,swagger
            - SPRING_CLOUD_CONFIG_URI=https://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_CLOUD_CONFIG_LABEL=master
            - SLEEP=40
            - LIQUIBASE_DROPFIRST=false
        ports:
            - 8444:8444
        volumes:
            - ./config:/config
    referenceservice-app:
        build: dockerfiles/referenceservice
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
            - SPRING_PROFILES_ACTIVE=development,swagger
            - SPRING_CLOUD_CONFIG_URI=https://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_CLOUD_CONFIG_LABEL=master
            - SLEEP=40
            - LIQUIBASE_DROPFIRST=true
        ports:
            - 8445:8445
        volumes:
            - ./config:/config
    candidateservice-app:
        build: dockerfiles/candidateservice
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
            - SPRING_PROFILES_ACTIVE=development,swagger
            - SPRING_CLOUD_CONFIG_URI=https://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_CLOUD_CONFIG_LABEL=master
            - SLEEP=40
            - LIQUIBASE_DROPFIRST=true
        ports:
            - 8446:8446
        volumes:
            - ./config:/config
    jobroom-batch:
        build: dockerfiles/jobroom_batch
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
            - SPRING_PROFILES_ACTIVE=development
            - SPRING_CLOUD_CONFIG_URI=https://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_CLOUD_CONFIG_LABEL=master
            - SLEEP=40
        ports:
            - 9000:9000
        volumes:
            - ./config:/config
            - batch-data:/build
            - /tmp/sftp-inbound:/tmp/sftp-inbound
    jobroom-postgresql:
        build: dockerfiles/postgresql
        ports:
            - 5432:5432
    jhipster-registry:
        build: dockerfiles/jhipster-registry
        environment:
            - JAVA_OPTS=-Xmx512m -Xms256m -Djavax.net.ssl.trustStore=/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
            - SECURITY_USER_PASSWORD=admin
            - SPRING_PROFILES_ACTIVE=development
            - GIT_URI=https://github.com/alv-ch/central-config.git
            - SPRING_CLOUD_CONFIG_PROFILE=development
            - SPRING_CLOUD_CONFIG_LABEL=master
            - ENCRYPT_KEY=5mA%R8G7@Xwt
        ports:
            - 8761:8761
        volumes:
            - ./config:/config
    jobroom-kibana:
        image: kibana:5
        ports:
          - 5601:5601
        environment:
            - xpack.security.enabled=false
        links:
          - jobroom-elasticsearch:elasticsearch
    jobroom-elasticsearch:
        image: elasticsearch:5
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
        command: -Ecluster.name=jobroom-cluster -Enetwork.host=0.0.0.0
        environment:
          - xpack.security.enabled=false
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        mem_limit: 1g
    mail-server:
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080

volumes:
    postgres-data:
        driver: local
    elasticsearch-data:
        driver: local
    batch-data:
        driver: local

