version: '3.3'
services:
    spring-cloud-dataflow:
        build: dockerfiles/spring-cloud-dataflow
        image: localhost:5000/spring-cloud-dataflow
        env_file: env.properties
        environment:
            SPRING_APPLICATION_NAME: spring-cloud-dataflow
#            SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
#            SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper:2181
        ports:
            - 9393:9393
            - 7000-7010:7000-7010
            - 20000-20010:20000-20010
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

    spring-cloud-dataflow-postgres:
        image: postgres:latest
        environment:
            TZ: Europe/Zurich
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: spring-cloud-dataflow
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        networks:
            - jobroom_data2
        volumes:
            - scdf-data:/var/lib/postgresql/data
        secrets:
            - postgres-passwd
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        deploy:
            placement:
                constraints: [node.labels.type == data]

volumes:
    scdf-data:
        driver: local

networks:
    jobroom_data2:
        external: true

secrets:
    bootstrap.yml-1:
        external: true
    postgres-passwd:
        external: true
