version: '3.4'
services:
    spring-boot-admin:
        image: localhost:5000/spring-boot-admin:latest
        env_file: env.properties
        environment:
            - LOGGING_PATH=/log
        ports:
            - 8001:8001
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
        deploy:
            placement:
                constraints: [node.labels.type == java]

networks:
    jobroom_data2:
        external: true

secrets:
    bootstrap.yml-1:
        external: true

