version: '3.3'
services:
    jhipster-registry:
        image: jhipster/jhipster-registry
        env_file: env.properties
        environment:
            - SPRING_PROFILES_ACTIVE=development
            - GIT_URI=https://github.com/alv-ch/central-config.git
            - SPRING_CLOUD_CONFIG_PROFILE=development
            - SECURITY_USER_PASSWORD=$${jhipster.registry.password}
        ports:
            - 8761:8761
        networks:
            - jobroom_data2
        secrets:
            - source: bootstrap.yml-1
              target: bootstrap.yml
            - truststore.jks
        command: java -Xmx512m -Xms256m -Duser.timezone=Europe/Zurich -Djava.security.egd=file:/dev/./urandom -jar /jhipster-registry.war --spring.cloud.config.server.git.uri=https://github.com/alv-ch/central-config.git
        deploy:
            placement:
                constraints: [node.labels.type == java]

    mail-server:
        image: schickling/mailcatcher
        env_file: env.properties
        ports:
            - 1025:1025
            - 1080:1080
        environment:
            - TZ=Europe/Zurich
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.type == infr]

    nginx-proxy:
        image: localhost:5000/nginx-lua
        env_file: env.properties
        ports:
            - target: 443
              published: 8443
              mode: host
        volumes:
            - nginx-error-pages:/var/errorpages
        configs:
            - source: nginx-default.conf
              target: /etc/nginx/conf.d/default.conf
        networks:
            - jobroom_data2
        secrets:
            - dev.job-room.ch.key
            - dev.job-room.ch.pem
        deploy:
            placement:
                constraints: [node.labels.type == java]

    zookeeper:
        image: zookeeper:3.5
        ports:
          - 2181:2181
        volumes:
            - zookeeper-data:/data
            - zookeeper-datalog:/datalog
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.type == infr]

    kafka:
        image: wurstmeister/kafka:1.0.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: dev.job-room.ch
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: dev.job-room.ch:2181
        ports:
            - 9092:9092
        volumes:
            - kafka-data:/kafka
        networks:
            - jobroom_data2
        depends_on:
            - zookeeper
        deploy:
            placement:
                constraints: [node.labels.type == infr]

    mockserver:
        image: jamesdbloom/mockserver:mockserver-5.3.0
        ports:
            - 9180:9180
        networks:
            - jobroom_data2
        environment:
            - LOG_LEVEL=DEBUG
        command: /opt/mockserver/run_mockserver.sh -serverPort 9180
        deploy:
            placement:
                constraints: [node.labels.type == infr]

networks:
    jobroom_data2:
        external: true

secrets:
    bootstrap.yml-1:
        external: true
    truststore.jks:
        external: true
    dev.job-room.ch.key:
        external: true
    dev.job-room.ch.pem:
        external: true

configs:
    nginx-default.conf:
        external: true

volumes:
    nginx-error-pages:
        driver: local
    zookeeper-data:
        driver: local
    zookeeper-datalog:
        driver: local
    kafka-data:
        driver: local
