version: '3.3'
services:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    jhipster-elasticsearch:
        build: jhipster-elasticsearch
        image: jhipster/jhipster-elasticsearch
        # Uncomment this section to have elasticsearch data loaded from a volume
        volumes:
            - log-data:/usr/share/elasticsearch/data
        deploy:
            placement:
                constraints: [node.labels.elk == apps]

    jhipster-logstash:
        image: jhipster/jhipster-logstash
        environment:
            - INPUT_TCP_PORT=5000
            - INPUT_UDP_PORT=5000
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=false
        ports:
            - 9600:9600
        depends_on:
            - jhipster-elasticsearch
        networks:
            - jobroom_data2
            - default
        deploy:
            placement:
                constraints: [node.labels.elk == apps]

    jhipster-console:
        build: jhipster-console
        image: jhipster/jhipster-console
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        ports:
            - 5602:5601
        depends_on:
            - jhipster-elasticsearch
        deploy:
            placement:
                constraints: [node.labels.elk == apps]

    #jhipster-import-dashboards:
    #    image: jhipster/jhipster-import-dashboards
    #    environment:
    #        - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
    #    networks:
    #        - elk
    #    depends_on:
    #        - jhipster-elasticsearch
    #    deploy:
    #        placement:
    #            constraints: [node.labels.elk == apps]

    # jhipster-alerter:
    #     build: jhipster-alerter/
    #     # Uncomment this section to enable alerting
    #     volumes:
    #         #- ./alerts/config.yaml:/opt/elastalert/config.yaml
    #         - ./alerts/rules/:/opt/elastalert/rules

    #https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configuration.html
    # jhipster-curator:
    #      build: jhipster-curator/
    #      environment:
    #          - ES_HOST=jhipster-elasticsearch
    #          - UNIT_COUNT=7
    #          - UNIT=days

    jhipster-zipkin:
        image: jhipster/jhipster-zipkin
        environment:
            - STORAGE_TYPE=mem
            - ES_HOSTS=http://jhipster-elasticsearch:9200
            - ZIPKIN_UI_LOGS_URL=http://dev.job-room.ch:5602/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())
        ports:
            - 9411:9411
        networks:
            - jobroom_data2
        deploy:
            placement:
                constraints: [node.labels.elk == apps]

volumes:
    log-data:
        driver: local

networks:
    jobroom_data2:
        external: true
